### ISSUE TITLE
Make FIX ME points clearer (Zig stage 1 compiler not clear enough)

### ISSUE THREAD

**Issue by ratfactor** [ratfactor/ziglings#124]
In cases such as Exercise 058, the current Zig compiler errors are downright misleading for newbies, which makes it way too frustrating to solve the expected issue. (Thanks to @alexgenaud for pointing this out specifically.)

I think this is also the source of the trouble with #120 (Exercise 065).

Instead of relying entirely on the compiler to lead Ziglings ~~victims~~ students to the right place to make a fix, these should be consistently pointed out with something like a comment with "FIX ME".

Additionally, consider expanding `???` sections to `??????...` to match the exact length of the expected answer to help out.

Maybe we can remove these extra hints when the Zig Stage 2 compiler comes out (since part of the idea of these exercises is to get you comfortable with reading the compiler's error messages)!

**Comment by chrboesch** [comment]
I am struggling with this right now and can give you an answer once I solve the quiz.

**Comment by chrboesch** [comment]
I figured out the solution, and after that I don't find it that hard anymore. Yes, it is indeed challenging, but hey, we are also in Quiz 7! And I found your tips very useful and sufficient to solve it. And the hint to the length was also very good. 

It's just not easy to find the balance between too easy and too hard. But we want to become "good" Zig developers, so a challenging lesson is also part of it. 

So at most an addition of FIX MEs, because the errors of the compiler are really quite confusing.
