### ISSUE TITLE
Request for exercise

### ISSUE THREAD

**Issue by Krvopije** [ratfactor/ziglings#171]
In the README it's mentioned that you want to limit ziglings to the language and don't make exercises for the standard library and so on.
I would love to have some exercises about importing libraries/other zig source files, building projects and stuff like that which in my opinion are also part of the language.

And of course a big thank you for ziglings, it is a great project and really fun.

**Comment by chrboesch** [comment]
Thank you for this hint, we will consider it.

**Comment by ratfactor** [comment]
Yeah, I don't really have anything against including exercises for those topics anymore. My hesitancy is just that they will definitely change more often than the core language. So it would be a bigger potential maintenance burden for Ziglings.

But since it's more than just me trying to keep up with it now, maybe that's not such a big problem. :smiley:

**Comment by chrboesch** [comment]
@ratfactor The first C exercise. I hope you agree. :smile:

**Comment by chrboesch** [comment]
@Krvopije You can try! :smile:

**Comment by Krvopije** [comment]
I like it!
