### ISSUE TITLE
Resolve minor formatting inconsistencies with `zig fmt`?

### ISSUE THREAD

**Issue by quexxon** [ratfactor/ziglings#21]
Several of the exercises have minor formatting inconsistencies:

```zig
// 11_while.zig (line 24)
    while ( ??? ){   // missing space before opening brace

// 13_while3.zig (line 24)
    while (n <= 20) : (n+=1) {   // condition has spaces around operator, continue expression does not

// etc.
```

Rather than depending on manual scanning to catch/fix these small issues, maybe it would be preferable to run `zig fmt` on the exercises _en masse_? It's a slightly more annoying job than it seems at first because most of the exercises have syntax errors as is (so the task requires temporarily fixing, reformatting, then un-fixing the exercises). If this approach seems sensible, I'm happy to undertake the work.

**Comment by ratfactor** [comment]
You read my mind on this one! I've been pondering using `zig fmt` since about exercise 30...

I'm really curious what these will look like after being fmted.  Hopefully they change very little. Obviously, the top priority is making sure that it's still clear what needs to be done in each exercise, but,the more I think about it, yeah, they should definitely be in a canonical form because that would be best for everybody involved. This needs to be done.

If you're up for giving it a go, you'll probably want to make use of my new system for creating and testing these things.

### Old and busted

What I used to do was:

1. Write the exercise and make it work
2. Break it
3. Fix it manually any time I needed to make a change, test it, re-break it :sob: 

### The new hotness

What I do now is:

1. Write the working exercise `answers/66_foo.zig`
2. Copy to `exercises/66_foo.zig` and break it
3. Run `patches/gollum.sh 66`, which creates `patches/patches/66_foo.patch` (output of `diff`)
4. Run `patches/eowyn.sh`, which applies patches to all exercises and puts them in `patches/healed` and runs `zig build` to test all of the exercises in `patches/healed`

```
|-- answers    <-- NOT in repo
|-- exercises
|-- patches
|   |-- healed    <-- NOT in repo
|   `-- patches
```

(See also the README in the patches dir.)

I've only just begun using this system, so only patches 1,2, and 45 (I think) have actual solutions. The rest are blank files.

I think the easiest way forward would be to (and keep in mind that this is off the top of my head, which doesn't always produce the best results):

* run `patches/eowyn.sh` (then don't run her again until you're all done!)
* fix everything in `patches/healed` and do the `zig fmt` on all of them too
* test as you go with `zig build -Dhealed`
* once that's done, `cp -r patches/healed answers`
* and `cp answers/* exercises/`
* break all the exercises again so they match the originals (within reason)
* run `patches/gollum.sh` in a loop (and remember, hissing is good :rofl: ) (untested: `for ex in exercises/*.zig; do ex=($basename $ex); patches/gollum.sh $ex; done`)
* finally, run `patches/eowyn.sh` _again_ to see if it all worked! :sweat_smile: 

Am I missing anything?

Let me know if you plan on starting this. (That would be amazing.)

Otherwise, I _was_ going to slowly go through and re-fix/break everything eventually anyway so the whole thing is testable with eowyn.  I could do a `zig fmt` at that time.  But it might be a little while before I get to that because I'm chomping at the bit to create some more exercises. :rocket: 

Thanks!

**Comment by quexxon** [comment]
Thanks for the notes! I can get to work on this.

**Comment by ratfactor** [comment]
That's fantastic. I'm really excited about that. Thanks!
