### ISSUE TITLE
Exercise 40's explanation on mutable/variable pointers could be improved

### ISSUE THREAD

**Issue by sawcce** [ratfactor/ziglings#215]
Exercise 40 states:

```
You can always make a constant pointer to a variable, but you cannot
make a variable pointer to a constant. This sounds like a logic puzzle,
but it just means that once data is declared immutable, you can't
coerce it to a mutable type. It's a safety thing (to prevent mistakes).
```

It seemed very confusing to me as I first read "You can always coerce a constant pointer to a variable pointer" when what I think was I was meant to understand was: "You can always make a constant pointer reference a variable but not a variable pointer that references a constant value".

It might just be a problem of comprehension (or just me being picky) on my side but I think the explanation could benefit a bit more clarity!

**Comment by ratfactor** [comment]
@sawcce You're right. The terminology is off. I checked with the most recent official Zig documentation, and `const` values are referred to as "const variables".  Obviously that's a bit of an oxymoron, but there you have it.

Instead of "constant" and "variable," to differentiate, we should probably use the terms "mutable" and "immutable".

Maybe:

```
You can always make a const pointer to a mutable value (var), but
you cannot make a var pointer to an immutable value (const).
This sounds like a logic puzzle, but it just means that once data
is declared immutable, you can't coerce it to a mutable type.
Think of mutable data as being volatile or even dangerous. Zig
always lets you be "more safe" and never "less safe."
```

What do you think?

**Comment by chrboesch** [comment]
@sawcce Thanks for this hint! :smile:
