### ISSUE TITLE
.gitignore: remove vim swap and backup files

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#251]
`.gitignore` has these entries:
```
*~
*.swp
```

However a better solution is to configure, in `vimrc`, `backupdir` and `directory`.
As an example, in my case I have:
```
set backupdir=$HOME/.local/state/vim/backup | call mkdir(&backupdir, 'p', 0700)
set directory=$HOME/.local/state/vim/swap   | call mkdir(&directory, 'p', 0700)
```

Using the new `XDG_STATE_HOME` directory.

Is it ok to remove them?

**Comment by ratfactor** [comment]
Sorry I didn't answer this quicker. It's been a while since I messed with `backupdir` and `directory` (specifically, before I started using a common "dotfiles" approach to share my .vimrc across computers).

Thanks for the reminder to give it a go again. This will clean up a lot of my projects. :+1: :smile:
