### ISSUE TITLE
Incorrect help message introduced in dbd42bb

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#294]
Commit dbd42bb updated the help message in Ziglings, instructing the user to use `zig build` instead of `zig build -Dn=n`.

The problem is that now running, e.g. `zig build -Dn=10 start`, will **also** show the same help message, that is wrong in this context.

@ratfactor In the same commit I also noted that you decided to show the hint message both in the case when there is a compile error and when the output doesn't not match.

This is an issue I was planning to discuss, since I'm not sure the same hint should be also shown in the second case.

UPDATE: the message "Look out! Broken programs below!" after the logo is probably incorrect, since it will be printed when all exercises have been healed, too.

UPDATE 2: using `std.os.exit(0)` instead of `std.os.exit(1)` also broke the unit test case 5 where I test that `zig build -Dn=1` prints the hint and exits with exit status 1.

The fix is easy (but I suspect that it will make the unit tests useless, since they can no longer detect an error), but I think that the your reason:
"Returning 0 'success' status because the *exercise* failed,  but Ziglings did not"
is wrong, since **it** was a build error (and `ZiglingStep` is a build step).  This is how the Zig Build System works (IMHO).

A possible solution is to change the exit code when running unit tests.

**Comment by perillo** [comment]
Fortunately there is a simple solution: using exit code 2:
https://github.com/ziglang/zig/blob/d70853b/src/main.zig#L4487

I'm updating the code to always use the new exit code.

The only issue remains with the compatibility check, since this special case was added in commit ziglang/zig@8acbfafef; probably it should die with exit code 0 (the `ci/compat.sh` script checks only the error message).

BTW: I'm also moving the ziglings logo definition from the `build` function scope to the global scope, making it public.  The reason is that the unit test needs to know how many lines must be skipped when the logo is printed.

**Comment by ratfactor** [comment]
@perillo Thank you for taking a careful look at this. :heart: 

1. If we can find a good fix for `zig build -Dn=10 start` showing a more correct message, that's great. However, the important thing is to make the *normal* experience as simple as possible. I'm much less concerned about the "advanced" experience (actually, I'm entirely unconcerned about the advanced experience since there are many ways to run these exercises outside of the build system entirely if one is so inclined).
2. Same hint message for compile error versus wrong output: Yes! I agree completely. I was thinking about that as well. I think separate hints (like `compile_hint` and `output_hint`?) would be much more helpful! :+1: 
3. "Look out! Broken programs below!" showing up after all exercises are healed: I did consider that. I'd be pretty surprised if it confused anyone who made it through all of the exercises. However, if we can make that not show up when you've completed everything, that would be even better.
4. Returning exit status 0: Sorry about the unit test! :frowning_face:  But having the extra error from the build system is a "no go" for me. People just trying to learn Zig shouldn't be subjected to any errors besides the compiler error for the exercise. Hopefully there's a good fix for this.

The end goal of Ziglings is to teach Zig. We do this by presenting raw output from the Zig compiler. The Zig compiler messages are much, much better than they used to be, but they can still be very overwhelming for a newbie. We need to do anything we can to keep this from being overwhelming.

In my opinion, whatever shows up when the learner first runs `zig build` for `001_hello.zig` is the most important part of the whole experience. :smile:

**Comment by perillo** [comment]
> @perillo Thank you for taking a careful look at this. heart
> 
>     1. If we can find a good fix for `zig build -Dn=10 start` showing a more correct message, that's great. However, the important thing is to make the _normal_ experience as simple as possible. I'm much less concerned about the "advanced" experience (actually, I'm entirely unconcerned about the advanced experience since there are many ways to run these exercises outside of the build system entirely if one is so inclined).

I agree.  I'm not even sure why *named exercise mode* was introduced...
I have some ideas in mind, but the current code is already rather complex, so I'm not sure adding more complexity is the right thing to do.

> 
>     2. Same hint message for compile error versus wrong output: Yes! I agree completely. I was thinking about that as well. I think separate hints (like `compile_hint` and `output_hint`?) would be much more helpful! +1

Ok.  The implementation is trivial, so it is not a problem.  When I have time I will try to run ziglings as an user (yes, I have yet to **use** ziglings from the user point of view).
> 
>     3. "Look out! Broken programs below!" showing up after all exercises are healed: I did consider that. I'd be pretty surprised if it confused anyone who made it through all of the exercises. However, if we can make that not show up when you've completed everything, that would be even better.
> 

We can use exercise 999 as a sentinel.

Thanks.

**Comment by ratfactor** [comment]
@perillo

* Avoiding additional complexity: 100%!  This thing is already pretty ridiculous. (Thus #296)
* Not using Ziglings - that's really funny. I was talking with @chrboesch about that the other day. I'm more of a book guy myself, but there is no Zig book. Making Ziglings was _my_ learning exercise. :laughing:

**Comment by ratfactor** [comment]
@perillo In that case, Zig is already perfect for you! :smile:

**Comment by perillo** [comment]
This issue has been fixed by 7c4bb9c.
