### ISSUE TITLE
Zigling 045

### ISSUE THREAD

**Issue by rvoogdgeert** [ratfactor/ziglings#358]
First a big _thank you_ for the admirable exercises, they are really helpful. 
I have a question about lines 32 and 34 in zigling 045. They are

```
const answer: u8 = result;
std.debug.print(fmt: "The Ultimate Answer: {}.\n", args: .{answer});
```

But in case the answer would be `result` and not a `u8`, which is the point of the zigling on _optionals_, I suppose, than line 42 can not print. 

So, wouldn't it be better to change these lines in:

```
const answer: ?u8 = result;
std.debug.print(fmt: "The Ultimate Answer: {any}.\n", args: .{answer});
```

With solution:

```
const answer: ?u8 = result orelse 42;
std.debug.print(fmt: "The Ultimate Answer: {any}.\n", args: .{answer});
```

**Comment by chrboesch** [comment]
> First a big thank you for the admirable exercises, they are really helpful. 

Thank's a lot! :smile: 

> So, wouldn't it be better to change these lines in: `const answer: ?u8 = result;`

No. Because if you do that, you'll be moving the simplification from the optional to the simple type. Sometimes it is helpful or necessary to have an optional type. But you should always try to avoid such declarations, because it makes it harder to understand the code. And so it's a good thing  to eliminate the option with just an `orelse` when it is possible. 

And besides, our example wouldn't work as well anymore. :wink:
